name: Python CI

on:
  push:
    branches:
      - main  # Ou toute autre branche que vous souhaitez surveiller
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu

    steps:
    # Étape 1: Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2: Installer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Utilisez la version de Python que vous préférez

    # Étape 3: Créer et activer l'environnement virtuel
    - name: Create and activate virtual environment
      run: |
        python -m venv venv  # Créer l'environnement virtuel
        source venv/bin/activate  # Activer l'environnement virtuel

    # Étape 4: Installer les dépendances (si vous avez un fichier requirements.txt)
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Réactiver l'environnement virtuel au cas où
        pip install -r requirements.txt  # Installer les dépendances

    # Étape 5: Exécuter les tests ou une autre commande
    - name: Run tests
      run: |
        source venv/bin/activate  # Assurez-vous que l'environnement est activé
        python -m unittest discover  # Exemple de tests Python, remplacez selon vos besoins

